# Generated by Django 5.2.4 on 2025-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinsession',
            name='repetitions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exerciseinsession',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
    ]
